version: 1
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        ClusterName: "testcluster"  # Your ECS cluster name
        ServiceName: "testservice"   # Your ECS service name
        TaskDefinition: "testTD:1"  # ECS task definition with the revision number
        LoadBalancerInfo:
          ContainerName: "mycontainer"  # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
