version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        ClusterName: ecspipelinecluster  # Your ECS cluster name
        ServiceName: ecsservice1  # Your ECS service name
        TaskDefinition: ecsTD:3  # ECS task definition with the revision number
        LoadBalancerInfo:
          ContainerName: mycontainer  # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
