version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: sampleTD:4
        LoadBalancerInfo:
          ContainerName: mycontainer
          ContainerPort: 80
