version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "sampleTD:8"  # Or use CodePipeline variable below
        LoadBalancerInfo:
          ContainerName: "mycontainer"
          ContainerPort: 80
